apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.label" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demo.{{ .Values.environment }}
      http:
        paths:
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.label" . }}-service
                port:
                  number: 8080
