apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.label" . }}-service
spec:
  selector:
    app: {{ include "app.label" . }}
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
